### ISSUE TITLE
Execution fails: Angular Elements

### ISSUE THREAD

**Issue by AHBAPAKA** [pnp/generator-spfx#169]
#### General Information
* [X] Usage

#### Specific generator
* [X] Angular Elements

#### What Version you are running?
* NodeJS: 10.15.2
* NPM:       3.10.10
* @pnp/generator-spfx: 1.6.3
* yo: 2.0.5
* gulp: 4.0.0
* @angular/cli: 7.3.4
* @microsoft/generator-sharepoint 1.7.1

#### Describe your problem
Generation WebPart with Angular Elements and getting this error. Tried multiple times, the same result:
-------------------------------------------------------------------------------------
A folder with solution name SPFX_0303-spfx will be created for you.
A component for the spo environment will be created for you.
Let's create a new SharePoint solution.
Found npm version 3.10.10
? Do you want to allow the tenant admin the choice of being able to deploy the solution to all sites immediately without running any feature deployment or adding apps in sites? No
? Which type of client-side component to create? (Use arrow keys)
? Which type of client-side component to create? WebPart
Add new Web part to solution spfx-0303-spfx.
? What is your Web part name? HelloWorld
? What is your Web part description? HelloWorld description
Overwriting an existing "Teams Manifest

   create config\package-solution.json
   create package.json
   create config\config.json
   create config\serve.json
   create tsconfig.json
   create .vscode\extensions.json
   create .vscode\launch.json
   create .vscode\settings.json
   create config\copy-assets.json
   create config\deploy-azure-storage.json
   create config\write-manifests.json
   create src\index.ts
   create gulpfile.js
   create README.md
   create tslint.json
   create .editorconfig
   create .gitignore
   create src\webparts\helloWorld\HelloWorldWebPart.module.scss
   create src\webparts\helloWorld\HelloWorldWebPart.ts
   create src\webparts\helloWorld\loc\en-us.js
   create src\webparts\helloWorld\loc\mystrings.d.ts
   create src\webparts\helloWorld\HelloWorldWebPart.manifest.json
   create .stylelintrc
   create azure-pipelines.yml
   create config\karma.config.js
   create tools\pre-version.js
Schematic input does not validate against the Schema: {"style":"scss","routing":false,"skipGit":true,"name":"SPFX_0303","version":"7.3.4"}
Errors:

  Data path ".name" should match format "html-selector".
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\PROJECTS\2019\SP\SPFX_0303\SPFX_0303\package.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at module.exports.install (C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\generators\angularelements\index.js:75:16)
    at Object.<anonymous> (C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\mansu\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
------------------------------------------------------------------------------------------------------------------

**Comment by AHBAPAKA** [comment]
![capture](https://user-images.githubusercontent.com/6142746/53703557-eecaa900-3dd8-11e9-8c21-05f3a979de6e.JPG)

**Comment by StfBauer** [comment]
@AHBAPAKA thank you for raising this issue. The problem is the underscore in the solution name, that is not properly handled during project creation. The error you see in the screenshot is raised by the angular/cli.

The screenshot first shows the error because of the underscore. The second execution was done without the underscore.

<img width="991" alt="screenshot 2019-03-04 at 22 51 32" src="https://user-images.githubusercontent.com/5503835/53765382-1fd9d500-3ed0-11e9-9c83-66fc2c85db8e.png">

For more information take a look at the [angular style guide](https://angular.io/guide/styleguide).

**Comment by kskramki** [comment]
Still no luck.. still getting error. upgraded  the MS generator as mention in the reply. there is no _ in solution, it adds - in solution. So any update?

'ng' is not recognized as an internal or external command,
operable program or batch file.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\tryout\PnPSPFx\pnpspfxangular\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at module.exports.install (C:\Users\testuser\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\generators\angularelements\index.js:75:16)
    at Object.<anonymous> (C:\Users\testuser\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\testuser\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\testuser\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\testuser\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
