### ISSUE TITLE
ng run bundle in Angular element app fails

### ISSUE THREAD

**Issue by kskramki** [pnp/generator-spfx#174]
Getting below error when try to run
ng run bundle
Cannot determine project or target for command.
Error: Cannot determine project or target for command.
    at RunCommand.initialize (D:\tryout\PnPSPFx\PnPSPFxAngular\node_modules\@angular\cli\models\architect-command.js:37:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by StfBauer** [comment]
@kskramki you mistyped the command.
Instead of:

```
ng run bundle
```

it should be:

```
npm run bundle
```
This command will then execute:

```
ng build --prod --output-hashing none && node elements-build.js
```

There is currently no custom builder configuration attached to the created angular projects.

**Comment by kskramki** [comment]
Got it. Thank you.
