### ISSUE TITLE
Creating Angular Elements project TypeError: paramCase is not a function

### ISSUE THREAD

**Issue by vinaunder** [pnp/generator-spfx#218]
#### General Information
* [x ] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS

#### What Version you are running?
* NodeJS: v10.18.0
* NPM:6.13.4
* @pnp/spfx: 1.10.2

#### UPDATE src/app/app.module.ts (495 bytes)

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: paramCase is not a function
    at module.exports.install (C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\generators\angularelements\index.js:119:43)
    at Object.<anonymous> (C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:402:23)
    at C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:403:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\E875708\AppData\Roaming\npm\node_modules\@pnp\generator-spfx\node_modules\yeoman-generator\lib\index.js:415:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by StfBauer** [comment]
Have you installed the generator with npm, pnpm or yarn? It seems like that not all dependencies required to run the generator have been installed.

Can you please check if you find the `param-case` does not exist in the node_modules folder in your path under C:\Users\E875708\AppData\Roaming\npm\node_modules@pnp\generator-spfx\

**Comment by vinaunder** [comment]
I have installed with npm, and folder param-case exists in node_modules.

**Comment by StfBauer** [comment]
Bug fixed in v1.11.0 Can you confirm, please? Thank you.
