### ISSUE TITLE
Unable to run gulp serve with VueJS

### ISSUE THREAD

**Issue by mghaleb** [pnp/generator-spfx#272]
#### General Information
* [x] Usage
* [ ] Development
* [ ] Documentation
* [ ] Feature Request
* [x] Bug

#### Specific generator
* [ ] Addons
* [ ] HandlebarsJS
* [x] VueJs

#### What Version you are running?
* NodeJS: v10.13.0
* NPM: 6.14.3
* @pnp/spfx:  @pnp/generator-spfx@1.15.0

When running `gulp serve` after generating a new project with VueJs, i get the following error!

Error message: 
```
{ ValidationError: ForkTsCheckerWebpackPlugin Invalid Options

options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties
options should NOT have additional properties

    at Object.validateOptions [as default] (E:\path\vueapp\node_modules\fork-ts-checker-webpack-plugin\node_modules\schema-utils\src\validateOptions.js:32:11)
    at new ForkTsCheckerWebpackPlugin (E:\path\vueapp\node_modules\fork-ts-checker-webpack-plugin\lib\ForkTsCheckerWebpackPlugin.js:28:31)
    at Object.<anonymous> (E:\path\vueapp\gulpfile.js:65:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)  
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireOrImport (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11)
    at execute (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:30:3)
    at Liftoff.handleArguments (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js:211:24)
    at Liftoff.execute (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:201:12)
    at module.exports (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:191:5)
  name: 'ValidationError',
  message:
   'ForkTsCheckerWebpackPlugin Invalid Options\n\noptions should NOT have additional properties\noptions should NOT have additional properties\noptions should NOT have additional properties\noptions should NOT have additional properties\n',
  errors:
 
   [ { keyword: 'additionalProperties',
       dataPath: '',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' },
     { keyword: 'additionalProperties',
       dataPath: '',
       schemaPath: '#/additionalProperties',
       params: [Object],
       message: 'should NOT have additional properties' } ] }
```
 
Package.json file details:

```

  "dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/pnpjs": "^2.0.6",
    "@pnp/spfx-property-controls": "1.19.0",
    "@types/jquery": "^3.5.0",
    "jquery": "^3.5.1",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^8.5.0"
  },
  "devDependencies": {
    "@microsoft/microsoft-graph-types": "^1.12.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@types/chai": "3.4.34",
    "@types/es6-promise": "0.0.33",
    "@types/mocha": "2.2.38",
    "@types/webpack-env": "1.13.1",
    "ajv": "~5.2.2",
    "fork-ts-checker-webpack-plugin": "^5.0.7",
    "gulp": "~3.9.1",
    "gulp-sequence": "1.0.0",
    "lodash": "^4.17.15",
    "sass-loader": "^8.0.2",
    "ts-loader": "^6.2.1",
    "vue-loader": "^15.9.3",
    "vue-template-compiler": "^2.6.11",
    "webpack-bundle-analyzer": "^3.8.0"
  }
```

**Comment by StfBauer** [comment]
It seems like you have used the TSLint option. Seems like there has something changed recently. We are looking into this.

In the meantime please comment out the following lines in your `gulpfile.js`
<img width="729" alt="Screenshot 2020-07-20 at 11 57 44" src="https://user-images.githubusercontent.com/5503835/87925362-75d8f980-ca80-11ea-9cc0-aecb4f910a16.png">

**Disable:**
```javascript
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
...
```

**Also later in the gulp file, you will find this:**
<img width="650" alt="Screenshot 2020-07-20 at 11 57 52" src="https://user-images.githubusercontent.com/5503835/87925531-b33d8700-ca80-11ea-84e1-d1860274b7c9.png">

Like I said we are looking into this and it should be fixed in the next version.

**Comment by mghaleb** [comment]
@StfBauer Thanks for the prompt reply. That seems to partly solve the issue, allowing the the command to run and code to work, but with the following error:
```
[17:57:02] Error - [webpack] 'dist':
./lib/webparts/vueapp/components/Vueapp.vue?vue&type=script&lang=ts& (./node_modules/ts-loader??ref--5!./node_modules/vue-loader/lib??vue-loader-options!./lib/webparts/vueapp/components/Vueapp.vue?vue&type=script&lang=ts&)
[tsl] ERROR
      TS5069: Option 'declarationMap' cannot be specified without specifying option 'declaration' or option 'composite'.
 @ ./lib/webparts/vueapp/components/Vueapp.vue?vue&type=script&lang=ts& 1:0-179 1:195-198 1:200-376 1:200-376
 @ ./lib/webparts/vueapp/components/Vueapp.vue
 @ ./lib/webparts/vueapp/VueappWebPart.js
```

When I tried to generate a new project without TSLint and the default TypeScript package, I ran into different errors. I was hoping to use @vuetifyjs in one of my projects, hence the use of VueJS. But might have to shelf it for now until the package is updated.

Thanks again  :-)

**Comment by StfBauer** [comment]
@mghaleb Can you share your sample project? This would be great and easier to debug for us.

**Comment by mghaleb** [comment]
@StfBauer  https://github.com/mghaleb/vue-spfx-debug  :-)
